apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-testfile
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,RGllcyBpc3QgZWluIFRlc3QK
        group:
          name: root
        mode: 420
        overwrite: true
        path: /etc/testfile
        user:
          name: root
